### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by JoaoGabrielCostaa** [ByteZ1337/ParticleLib#15]
Why?

Error log: [https://pastebin.com/tJ2NvfhB](https://pastebin.com/tJ2NvfhB)

My code:
```java
private boolean isValidParticle(String particle) {
		try {
			ParticleEffect.valueOf(particle);
			return true;
		} catch (Exception e) {
			return false;
		}
}
```

**Comment by ByteZ1337** [comment]
Do you use a custom ClassLoader by any chance?

**Comment by JoaoGabrielCostaa** [comment]
Yeah, i have a custom class loader running my plugins

**Comment by ByteZ1337** [comment]
Well, that is the issue here. I'm using the plugin field in the [PluginClassLoader](https://papermc.io/javadocs/paper/1.17/org/bukkit/plugin/java/PluginClassLoader.html) to retrieve the plugin, that belongs to ParticleLib. This plugin instance is needed to register Listeners and start [tasks](https://github.com/ByteZ1337/ParticleLib/wiki/ParticleTasks).

I might add a setter for the plugin in the future, but in the meantime, you have to load the ReflectionUtils class with the normal Bukkit ClassLoader. To do that, just add a simple method call that does nothing (like ``ReflectionUtils.existsClass("");``) to your onEnable method. Let me know if that fixes your issue for now.

**Comment by ByteZ1337** [comment]
You can now set the ``ReflectionUtils#plugin`` field in [1.6.4](https://github.com/ByteZ1337/ParticleLib/releases/tag/1.6.4).
